version: '3'
services:
  service-a:
    build:
      context: ./service-a
    container_name: service-a
    environment:
      - SERVICE_NAME=Service-A
      - SERVICE_PORT=8081
    ports:
      - "8081:8081"
    networks:
      - microservice-network

  service-b:
    build:
      context: ./service-b
    container_name: service-b
    environment:
      - SERVICE_NAME=Service-B
      - SERVICE_PORT=8082
    ports:
      - "8082:8082"
    networks:
      - microservice-network

  service-c:
    build:
      context: ./service-c
    container_name: service-c
    environment:
      - SERVICE_NAME=Service-C
      - SERVICE_PORT=8083
    ports:
      - "8083:8083"
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge

