services:
  eureka-server:
    build:
      context: ./eureka-servicediscovery
    ports:
      - "8761:8761"
    networks:
      - eureka-network
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  vertx-rest-eurekaclient:
    build:
      context: ./vertx-rest-eurekaclient
    ports:
      - "8081:8081"
    networks:
      - eureka-network
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    entrypoint: ["sh", "-c", "sleep 1 && java -jar app.jar"]

networks:
  eureka-network:
    driver: bridge