services:
  eureka-server:
    build:
      context: .
    image: eureka-server:latest
    ports:
      - "8761:8761"
    networks:
      - eureka-network
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false

networks:
  eureka-network:
    driver: bridge
