server:
  port: ${API_GATEWAY_EUREKA_INSTANCE_PORT}

spring:
  application:
    name: ${API_GATEWAY_EUREKA_INSTANCE_HOSTNAME}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    registerWithEureka: true
    fetchRegistry: true

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG