server:
  port: 8081  # Gateway will run on port 8081

spring:
  application:
    name: api-gateway  # Gateway name for Eureka registration

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable dynamic routing based on Eureka services
      routes:
        - id: vertx-service
          uri: lb://VERTX-SERVICE  # Use the Eureka service name (case-insensitive)
          predicates:
            - Path=/vertx-service/**  # Route requests to /vertx-service/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # Eureka server location
    registerWithEureka: true  # Gateway registers with Eureka
    fetchRegistry: true       # Gateway fetches Eureka registry

logging:
  level:
    org.springframework.cloud.gateway: DEBUG  # Optional: Debug logging for the gateway
