
services:
  eureka-server:
    build:
      context: ./eureka-servicediscovery
    ports:
      - "8761:8761"
    networks:
      - eureka-network
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  map-microservice:
      build:
        context: ./map_microservice
      ports:
        - "8087:8087"
      networks:
        - eureka-network
      depends_on:
        eureka-server:
          condition: service_healthy
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
        - EUREKA_HOST=eureka-server
        - EUREKA_PORT=8761
        - SERVICE_HOST=map-microservice
        - SERVICE_PORT=8087
        - COMM_MICROSERVICES_PORT=8088
      healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:8087/health || exit 1", "curl -f http://localhost:8088/health || exit 1"]
        interval: 10s
        timeout: 5s
        retries: 3
        start_period: 10s

  mongodb-ebike:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - eureka-network
    environment:
      - GLIBC_TUNABLES=glibc.pthread.rseq=0
    volumes:
      - mongodb_data:/data/db
    command: --wiredTigerCacheSizeGB 1
    ulimits:
      memlock: -1
    deploy:
      resources:
        limits:
          memory: 1G
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  ebike-microservice:
    build:
      context: ./ebike_microservice
    ports:
      - "8080:8080"
    networks:
      - eureka-network
    depends_on:
      eureka-server:
        condition: service_healthy
      mongodb-ebike:
        condition: service_healthy
      map-microservice:
        condition: service_healthy
    environment:
      - MONGO_CONNECTION=mongodb://mongodb-ebike:27017
      - EUREKA_HOST=eureka-server
      - EUREKA_PORT=8761
      - SERVICE_HOST=ebike-service
      - SERVICE_PORT=8080
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  ride-microservice:
    build:
      context: ./ride_microservice
    ports:
      - "8092:8092"
    networks:
      - eureka-network
    depends_on:
      eureka-server:
        condition: service_healthy
      ebike-microservice:
        condition: service_healthy
      user-microservice:
        condition: service_healthy
      map-microservice:
        condition: service_healthy
    environment:
      - EUREKA_HOST=eureka-server
      - EUREKA_PORT=8761
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8092/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  user-microservice:
    build:
      context: ./user_microservice
    ports:
      - "8082:8082"
    networks:
      - eureka-network
    depends_on:
      eureka-server:
        condition: service_healthy
      mongodb-ebike:
        condition: service_healthy
    environment:
      - EUREKA_HOST=eureka-server
      - EUREKA_PORT=8761
      - SERVICE_HOST=user-microservice
      - SERVICE_PORT=8082
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  api-gateway:
    build:
      context: ./eureka-apigateway  # Path to your API Gateway Dockerfile
    ports:
      - "8081:8081"  # Gateway runs on port 8081
    networks:
      - eureka-network
    depends_on:
      eureka-server:
        condition: service_healthy
      ebike-microservice:
        condition: service_healthy
      user-microservice:
        condition: service_healthy
      map-microservice:
        condition: service_healthy
      ride-microservice:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_APPLICATION_NAME=api-gateway  # Gateway service name

networks:
  eureka-network:
    driver: bridge

volumes:
  mongodb_data:
