
services:
  eureka-server:
    build:
      context: ./eureka-servicediscovery
    ports:
      - "8761:8761"
    networks:
      - eureka-network
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  vertx-rest-eurekaclient:
    build:
      context: ./vertx-rest-eurekaclient
    ports:
      - "8080:8080"
    networks:
      - eureka-network
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  api-gateway:
    build:
      context: ./eureka-apigateway  # Path to your API Gateway Dockerfile
    ports:
      - "8081:8081"  # Gateway runs on port 8081
    networks:
      - eureka-network
    depends_on:
      eureka-server:
        condition: service_healthy
      vertx-rest-eurekaclient:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_APPLICATION_NAME=api-gateway  # Gateway service name

networks:
  eureka-network:
    driver: bridge
